blueprint:
  name: Detect Shower Using Light and Water Usage (No Extra Sensors)
  description: >
    Detect when a shower is in progress based on bathroom light + water usage delta.
    No template or statistics sensors required.
  domain: automation
  input:
    bathroom_switch:
      name: Bathroom Light Switch
      selector:
        entity:
          domain: switch
    water_sensor:
      name: Water Usage Sensor
      selector:
        entity:
          domain: sensor
          device_class: water
    water_delta:
      name: Water Usage Delta
      description: Minimum increase in water usage (e.g. 0.1 for 100 liters)
      default: 0.1
      selector:
        number:
          min: 0.01
          max: 5.0
          step: 0.01
          unit_of_measurement: "m³ or 100 L"
    wait_time:
      name: Wait Time After Light Turns On
      description: Wait before checking water delta (to allow usage to accumulate)
      default: 60
      selector:
        number:
          min: 10
          max: 300
          step: 10
          unit_of_measurement: seconds
    shower_switch:
      name: Switch to Turn On When Shower Detected
      selector:
        entity:
          domain: switch

mode: single

trigger:
  - platform: state
    entity_id: !input bathroom_switch
    to: "on"

variables:
  initial_usage: "{{ states[inputs.water_sensor] | float }}"

action:
  - delay:
      seconds: !input wait_time

  - variables:
      current_usage: "{{ states[inputs.water_sensor] | float }}"
      usage_diff: "{{ current_usage - initial_usage }}"

  - condition: template
    value_template: "{{ usage_diff > inputs.water_delta | float }}"

  - service: switch.turn_on
    target:
      entity_id: !input shower_switch
