blueprint:
  name: DEBUG - Shower Detection (Always Triggers)
  description: Debug version that always triggers to test the automation
  domain: automation
  input:
    bathroom_switch:
      name: Bathroom Light Switch
      selector:
        entity:
          domain: switch
    water_sensor:
      name: Water Usage Sensor
      selector:
        entity:
          domain: sensor
          device_class: water
    shower_switch:
      name: Switch to Turn On When Shower Detected
      selector:
        entity:
          domain: switch

mode: single

trigger:
  - platform: state
    entity_id: !input bathroom_switch
    to: "on"

action:
  # Log initial water usage
  - service: system_log.write
    data:
      message: "DEBUG: Light turned on. Initial water usage: {{ states(input_water_sensor) }}"
      level: warning
  
  # Always turn on the shower switch for testing
  - service: switch.turn_on
    target:
      entity_id: !input shower_switch
      
  # Log that we completed
  - service: system_log.write
    data:
      message: "DEBUG: Shower switch turned on successfully"
      level: warning
